language: android
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
addons:
  artifacts:
    paths:
    - $(ls app/build/outputs/apk/WiFiAfterConnect-debug-*.apk)
    - $(ls travis-build-*)

android:
   components:
   - android-22
   - build-tools-22.0.1
   - tools
   - platform-tools
   - extras
   - extra-android-m2repository
   - extra-android-support

script:
  - ./gradlew clean coverage -S
  - if [ "$TRAVIS_JDK_VERSION" == 'oraclejdk8' ]; then ./gradlew assembleDebug; fi
  - if [ "$TRAVIS_JDK_VERSION" == 'oraclejdk8' ]; then touch "travis-build-$TRAVIS_BUILD_NUMBER-$TRAVIS_BUILD_ID"; fi

after_success:
  - ./gradlew coveralls
