language: android
jdk: oraclejdk7

android:
   components:
   - platform-tools
   - extra-android-support
   - android-22
   - build-tools-22.0.1

script:
  - ./gradlew coverage -S

after_success:
  - ./gradlew coveralls
