language: android
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
addons:
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk

android:
   components:
   - android-22
   - build-tools-22.0.1
   - tools
   - platform-tools
   - extras
   - extra-android-m2repository
   - extra-android-support

script:
  - ./gradlew clean assembleDebug coverage -S

after_success:
  - ./gradlew coveralls
